/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class AjudaEstuProf extends javax.swing.JFrame {

    /**
     * Creates new form AjudaEstuProf
     */
    public AjudaEstuProf() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1DescricaoDoProblema = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1ProblemaNaBiblioteca = new javax.swing.JButton();
        jButton2EnviarAjuda = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2ObjetoDoProblema = new javax.swing.JTextField();
        jButton3ProblemaNoSite = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 22)); // NOI18N
        jLabel2.setText("ACONTECEU:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jTextField1DescricaoDoProblema.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1DescricaoDoProblema.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField1DescricaoDoProblema.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1DescricaoDoProblema.setToolTipText("Descreva o ocorrido");
        jTextField1DescricaoDoProblema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField1DescricaoDoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 220, 100));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 22)); // NOI18N
        jLabel3.setText("NA BIBLIOTECA?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 22)); // NOI18N
        jLabel4.setText("OCORREU NO SITE OU ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jButton1ProblemaNaBiblioteca.setBackground(new java.awt.Color(255, 204, 255));
        jButton1ProblemaNaBiblioteca.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1ProblemaNaBiblioteca.setText("BIBLIOTECA");
        getContentPane().add(jButton1ProblemaNaBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 140, 50));

        jButton2EnviarAjuda.setBackground(new java.awt.Color(255, 204, 255));
        jButton2EnviarAjuda.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2EnviarAjuda.setText("ENVIAR");
        getContentPane().add(jButton2EnviarAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 140, 50));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 22)); // NOI18N
        jLabel5.setText("O PROBLEMA FOI COM:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 22)); // NOI18N
        jLabel6.setText("EXPLIQUE O QUE ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jTextField2ObjetoDoProblema.setBackground(new java.awt.Color(255, 204, 255));
        jTextField2ObjetoDoProblema.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField2ObjetoDoProblema.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2ObjetoDoProblema.setToolTipText("Livro, ambiente, funcionário, etc.");
        jTextField2ObjetoDoProblema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField2ObjetoDoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, 80));

        jButton3ProblemaNoSite.setBackground(new java.awt.Color(255, 204, 255));
        jButton3ProblemaNoSite.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton3ProblemaNoSite.setText("SITE");
        jButton3ProblemaNoSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ProblemaNoSiteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3ProblemaNoSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 140, 50));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entrar em contato:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bibliotecafdg@hotmail.br");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(12) 00000-0000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horário de funcionamento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 452, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Segunda à sexta: 8:00 até 20:00  ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 467, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sábado, Domingo e Feriados: 9::00 até 12:00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/BARRA PINCEL DOAÇAO.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/AJUDA ALUNOPROFESSOR.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ProblemaNoSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ProblemaNoSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ProblemaNoSiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjudaEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjudaEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjudaEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjudaEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjudaEstuProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ProblemaNaBiblioteca;
    private javax.swing.JButton jButton2EnviarAjuda;
    private javax.swing.JButton jButton3ProblemaNoSite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1DescricaoDoProblema;
    private javax.swing.JTextField jTextField2ObjetoDoProblema;
    // End of variables declaration//GEN-END:variables
}
