/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class ObrasSelecionadasEstuProf extends javax.swing.JFrame {

    /**
     * Creates new form ObrasSelecionadas
     */
    public ObrasSelecionadasEstuProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1NumDeCopiasDisp = new javax.swing.JTextField();
        jTextField2TituloSelecionado = new javax.swing.JTextField();
        jTextField3DataPubliDoTituloSelec = new javax.swing.JTextField();
        jTextField4EditoraDoTituloSelec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5AutorDoTituloSelec = new javax.swing.JTextField();
        jButton1Emprestimo = new javax.swing.JButton();
        jButton2Voltar = new javax.swing.JButton();
        jTextField6TituloSelecionado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel2.setText("OBRA SELECIONADA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jTextField1NumDeCopiasDisp.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1NumDeCopiasDisp.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField1NumDeCopiasDisp.setToolTipText("Número de cópias disponíveis");
        getContentPane().add(jTextField1NumDeCopiasDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 70, 30));

        jTextField2TituloSelecionado.setBackground(new java.awt.Color(255, 204, 255));
        jTextField2TituloSelecionado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField2TituloSelecionado.setToolTipText("Título da obra selecionada");
        getContentPane().add(jTextField2TituloSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 192, 270, 30));

        jTextField3DataPubliDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField3DataPubliDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField3DataPubliDoTituloSelec.setToolTipText("Data de publicação da obra selecionada");
        jTextField3DataPubliDoTituloSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3DataPubliDoTituloSelecActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3DataPubliDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 350, 190, 30));

        jTextField4EditoraDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField4EditoraDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField4EditoraDoTituloSelec.setToolTipText("Editora da obra selecionada");
        getContentPane().add(jTextField4EditoraDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 310, 190, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("N° de cópias disponíveis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 247, -1, -1));

        jTextField5AutorDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField5AutorDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField5AutorDoTituloSelec.setToolTipText("Autor da obra selecionada");
        getContentPane().add(jTextField5AutorDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 270, 190, 30));

        jButton1Emprestimo.setBackground(new java.awt.Color(255, 204, 255));
        jButton1Emprestimo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1Emprestimo.setText("EMPRÉSTIMO");
        getContentPane().add(jButton1Emprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 150, 40));

        jButton2Voltar.setBackground(new java.awt.Color(255, 204, 255));
        jButton2Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2Voltar.setText("VOLTAR");
        getContentPane().add(jButton2Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 100, 40));

        jTextField6TituloSelecionado.setBackground(new java.awt.Color(255, 204, 255));
        jTextField6TituloSelecionado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField6TituloSelecionado.setToolTipText("Título da obra selecionada");
        getContentPane().add(jTextField6TituloSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 220, 60));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entrar em contato:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bibliotecafdg@hotmail.br");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(12) 00000-0000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horário de funcionamento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 452, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Segunda à sexta: 8:00 até 20:00  ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 467, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sábado, Domingo e Feriados: 9::00 até 12:00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/BARRA PINCEL DOAÇAO.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/obra selecionada estudanteprofessor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3DataPubliDoTituloSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3DataPubliDoTituloSelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3DataPubliDoTituloSelecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrasSelecionadasEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrasSelecionadasEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrasSelecionadasEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrasSelecionadasEstuProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObrasSelecionadasEstuProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Emprestimo;
    private javax.swing.JButton jButton2Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1NumDeCopiasDisp;
    private javax.swing.JTextField jTextField2TituloSelecionado;
    private javax.swing.JTextField jTextField3DataPubliDoTituloSelec;
    private javax.swing.JTextField jTextField4EditoraDoTituloSelec;
    private javax.swing.JTextField jTextField5AutorDoTituloSelec;
    private javax.swing.JTextField jTextField6TituloSelecionado;
    // End of variables declaration//GEN-END:variables
}
