/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class DoaçõesObrasEstProf extends javax.swing.JFrame {

    /**
     * Creates new form DoaçõesObrasEstProf
     */
    public DoaçõesObrasEstProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1TítuloObra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2EditoraDaObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3AutorDaObra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4DataPublicacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5AreaObra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6NumExemplares = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7Estado = new javax.swing.JTextField();
        jButton1Voltar = new javax.swing.JButton();
        jButton2EnviarDoacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setText("DOAÇÕES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jTextField1TítuloObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1TítuloObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField1TítuloObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1TítuloObra.setToolTipText("Título da Obra");
        jTextField1TítuloObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TítuloObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1TítuloObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel3.setText("EDITORA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("TÍTULO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jTextField2EditoraDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2EditoraDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField2EditoraDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2EditoraDaObra.setToolTipText("Editora da Obra");
        getContentPane().add(jTextField2EditoraDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("AUTOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jTextField3AutorDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3AutorDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField3AutorDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3AutorDaObra.setToolTipText("Autor da Obra");
        getContentPane().add(jTextField3AutorDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel6.setText("DATA DE PUBLICAÇÃO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jTextField4DataPublicacao.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4DataPublicacao.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField4DataPublicacao.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4DataPublicacao.setToolTipText("Data de Publicação da Obra");
        getContentPane().add(jTextField4DataPublicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("ÁREA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jTextField5AreaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5AreaObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField5AreaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5AreaObra.setToolTipText("Área do Tema da Obra");
        getContentPane().add(jTextField5AreaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel8.setText("N° DE EXEMPLARES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 30));

        jTextField6NumExemplares.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6NumExemplares.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField6NumExemplares.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6NumExemplares.setToolTipText("N° de Exemplares A Serem Doados");
        getContentPane().add(jTextField6NumExemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 160, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel9.setText("ESTADO DO LIVRO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jTextField7Estado.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7Estado.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField7Estado.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7Estado.setToolTipText("Usado ou Novo");
        getContentPane().add(jTextField7Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 160, 30));

        jButton1Voltar.setBackground(new java.awt.Color(255, 204, 255));
        jButton1Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton1Voltar.setText("VOLTAR");
        getContentPane().add(jButton1Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 100, 40));

        jButton2EnviarDoacao.setBackground(new java.awt.Color(255, 204, 255));
        jButton2EnviarDoacao.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton2EnviarDoacao.setText("ENVIAR");
        getContentPane().add(jButton2EnviarDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 100, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/doações ESTUDANTESPROFESSORES.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1TítuloObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TítuloObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TítuloObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoaçõesObrasEstProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoaçõesObrasEstProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoaçõesObrasEstProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoaçõesObrasEstProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoaçõesObrasEstProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Voltar;
    private javax.swing.JButton jButton2EnviarDoacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1TítuloObra;
    private javax.swing.JTextField jTextField2EditoraDaObra;
    private javax.swing.JTextField jTextField3AutorDaObra;
    private javax.swing.JTextField jTextField4DataPublicacao;
    private javax.swing.JTextField jTextField5AreaObra;
    private javax.swing.JTextField jTextField6NumExemplares;
    private javax.swing.JTextField jTextField7Estado;
    // End of variables declaration//GEN-END:variables
}
