/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class SolicitacaoObrasProfEst extends javax.swing.JFrame {

    /**
     * Creates new form SolicitacaoObrasProfEst
     */
    public SolicitacaoObrasProfEst() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1TituloObra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2EditoraObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3AutorObra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4AnoObra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5AreaObra = new javax.swing.JTextField();
        jButton1Voltar = new javax.swing.JButton();
        jButton2SolicitarObra = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 33)); // NOI18N
        jLabel2.setText("SOLICITAÇÃO DE OBRAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 27, -1, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel3.setText("TÍTULO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jTextField1TituloObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1TituloObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField1TituloObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1TituloObra.setToolTipText("Título da Obra");
        jTextField1TituloObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TituloObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1TituloObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 180, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("EDITORA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jTextField2EditoraObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2EditoraObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField2EditoraObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2EditoraObra.setToolTipText("Editora da Obra");
        jTextField2EditoraObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EditoraObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2EditoraObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("AUTOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jTextField3AutorObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3AutorObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField3AutorObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3AutorObra.setToolTipText("Autor da Obra");
        getContentPane().add(jTextField3AutorObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 333, 180, 40));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel6.setText("ANO DE PUBLICAÇÃO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jTextField4AnoObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4AnoObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField4AnoObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4AnoObra.setToolTipText("Ano de Publicação da Obra");
        getContentPane().add(jTextField4AnoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("ÁREA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 60, -1));

        jTextField5AreaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5AreaObra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField5AreaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5AreaObra.setToolTipText("Área do Tema da Obra");
        getContentPane().add(jTextField5AreaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 40));

        jButton1Voltar.setBackground(new java.awt.Color(255, 204, 255));
        jButton1Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton1Voltar.setText("VOLTAR");
        jButton1Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 90, 20));

        jButton2SolicitarObra.setBackground(new java.awt.Color(255, 204, 255));
        jButton2SolicitarObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2SolicitarObra.setText("SOLICITAR");
        getContentPane().add(jButton2SolicitarObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 331, 130, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entrar em contato:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bibliotecafdg@hotmail.br");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(12) 00000-0000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horário de funcionamento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 452, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Segunda à sexta: 8:00 até 20:00  ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 467, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sábado, Domingo e Feriados: 9::00 até 12:00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/tinteiro.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/SOLICITAÇÃO obras EstProf.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2EditoraObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EditoraObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2EditoraObraActionPerformed

    private void jTextField1TituloObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TituloObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TituloObraActionPerformed

    private void jButton1VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitacaoObrasProfEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitacaoObrasProfEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitacaoObrasProfEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitacaoObrasProfEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitacaoObrasProfEst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Voltar;
    private javax.swing.JButton jButton2SolicitarObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1TituloObra;
    private javax.swing.JTextField jTextField2EditoraObra;
    private javax.swing.JTextField jTextField3AutorObra;
    private javax.swing.JTextField jTextField4AnoObra;
    private javax.swing.JTextField jTextField5AreaObra;
    // End of variables declaration//GEN-END:variables
}
