/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class AdicaoObrasBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form AdicaoObrasBibliotecario
     */
    public AdicaoObrasBibliotecario() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1DataPublicacaoDaObra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2EstadoDaObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3EditoraDaObra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4AutorDaObra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5TituloDaObra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6AreaDaObra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7NumDeExDaObra = new javax.swing.JTextField();
        jButton1EnviarNovaObra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel2.setText("ADIÇÃO DE OBRAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel3.setText("DATA DE PUBLICAÇÃO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jTextField1DataPublicacaoDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1DataPublicacaoDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField1DataPublicacaoDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1DataPublicacaoDaObra.setToolTipText("Data de publicação da obra que deseja");
        jTextField1DataPublicacaoDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1DataPublicacaoDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1DataPublicacaoDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 160, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("ÁREA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jTextField2EstadoDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2EstadoDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField2EstadoDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2EstadoDaObra.setToolTipText("Usado ou Novo");
        jTextField2EstadoDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2EstadoDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2EstadoDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 160, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("ESTADO DO LIVRO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jTextField3EditoraDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3EditoraDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField3EditoraDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3EditoraDaObra.setToolTipText("Editora da obra que deseja");
        jTextField3EditoraDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3EditoraDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3EditoraDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel6.setText("AUTOR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jTextField4AutorDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4AutorDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField4AutorDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4AutorDaObra.setToolTipText("Autor da obra que deseja");
        jTextField4AutorDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4AutorDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4AutorDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("TÍTULO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jTextField5TituloDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5TituloDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField5TituloDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5TituloDaObra.setToolTipText("Nome da obra que deseja");
        jTextField5TituloDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5TituloDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5TituloDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel8.setText("EDITORA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jTextField6AreaDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6AreaDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField6AreaDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6AreaDaObra.setToolTipText("Área da obra que deseja");
        jTextField6AreaDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6AreaDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6AreaDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel9.setText("N° DE EXEMPLARES");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jTextField7NumDeExDaObra.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7NumDeExDaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField7NumDeExDaObra.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7NumDeExDaObra.setToolTipText("N° de exemplares da obra que deseja");
        jTextField7NumDeExDaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7NumDeExDaObraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7NumDeExDaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 160, 30));

        jButton1EnviarNovaObra.setBackground(new java.awt.Color(0, 0, 0));
        jButton1EnviarNovaObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1EnviarNovaObra.setForeground(new java.awt.Color(255, 255, 255));
        jButton1EnviarNovaObra.setText("ENVIAR");
        getContentPane().add(jButton1EnviarNovaObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/adição obras bibliotecario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1DataPublicacaoDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1DataPublicacaoDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1DataPublicacaoDaObraActionPerformed

    private void jTextField2EstadoDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2EstadoDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2EstadoDaObraActionPerformed

    private void jTextField3EditoraDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3EditoraDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3EditoraDaObraActionPerformed

    private void jTextField4AutorDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4AutorDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4AutorDaObraActionPerformed

    private void jTextField5TituloDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5TituloDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5TituloDaObraActionPerformed

    private void jTextField6AreaDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6AreaDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6AreaDaObraActionPerformed

    private void jTextField7NumDeExDaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7NumDeExDaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7NumDeExDaObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicaoObrasBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicaoObrasBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicaoObrasBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicaoObrasBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicaoObrasBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1EnviarNovaObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1DataPublicacaoDaObra;
    private javax.swing.JTextField jTextField2EstadoDaObra;
    private javax.swing.JTextField jTextField3EditoraDaObra;
    private javax.swing.JTextField jTextField4AutorDaObra;
    private javax.swing.JTextField jTextField5TituloDaObra;
    private javax.swing.JTextField jTextField6AreaDaObra;
    private javax.swing.JTextField jTextField7NumDeExDaObra;
    // End of variables declaration//GEN-END:variables
}
