/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class FilaDeEspera extends javax.swing.JFrame {

    /**
     * Creates new form FilaDeEspera
     */
    public FilaDeEspera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1TempDeEspera = new javax.swing.JTextField();
        jTextField1TítuloObra1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1TamFila1 = new javax.swing.JTextField();
        jButton1EntrarNaFila = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1TempDeEspera.setBackground(new java.awt.Color(153, 0, 204));
        jTextField1TempDeEspera.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jTextField1TempDeEspera.setToolTipText("Tempo de espera para empréstimo em semanas");
        jTextField1TempDeEspera.setBorder(null);
        jTextField1TempDeEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TempDeEsperaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1TempDeEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 60, 50));

        jTextField1TítuloObra1.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1TítuloObra1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jTextField1TítuloObra1.setToolTipText("Título da obra selecionada");
        getContentPane().add(jTextField1TítuloObra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 290, 90));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel2.setText("TEMPO DE ESPERA EM SEMANAS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("N° DE PESSOAS NA FILA DE ESPERA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 270, -1, -1));

        jTextField1TamFila1.setBackground(new java.awt.Color(153, 0, 204));
        jTextField1TamFila1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jTextField1TamFila1.setToolTipText("Número de pessoas na fila ");
        jTextField1TamFila1.setBorder(null);
        jTextField1TamFila1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TamFila1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1TamFila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 60, 50));

        jButton1EntrarNaFila.setBackground(new java.awt.Color(255, 204, 255));
        jButton1EntrarNaFila.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton1EntrarNaFila.setText("ENTRAR NA FILA");
        getContentPane().add(jButton1EntrarNaFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, 30));

        jButton2Cancelar.setBackground(new java.awt.Color(255, 204, 255));
        jButton2Cancelar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton2Cancelar.setText("CANCELAR");
        getContentPane().add(jButton2Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 30));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entrar em contato:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bibliotecafdg@hotmail.br");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(12) 00000-0000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horário de funcionamento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 452, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Segunda à sexta: 8:00 até 20:00  ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 467, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sábado, Domingo e Feriados: 9::00 até 12:00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/BARRA PINCEL DOAÇAO.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/FILA DE ESPERA.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1TempDeEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TempDeEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TempDeEsperaActionPerformed

    private void jTextField1TamFila1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TamFila1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TamFila1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaDeEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaDeEspera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1EntrarNaFila;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1TamFila1;
    private javax.swing.JTextField jTextField1TempDeEspera;
    private javax.swing.JTextField jTextField1TítuloObra1;
    // End of variables declaration//GEN-END:variables
}
