/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class RespostaDeAjudaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form RespostaDeAjudaFuncionario
     */
    public RespostaDeAjudaFuncionario() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1RespostaDoFuncionario = new javax.swing.JTextField();
        jButton1EnviarResposta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField2TopicoProblema = new javax.swing.JTextField();
        jTextField3BibliotecaOuSite = new javax.swing.JTextField();
        jTextField4DescricaoDoProblema = new javax.swing.JTextField();
        jTextField5NomeOuAnonimo = new javax.swing.JTextField();
        jTextField6Status = new javax.swing.JTextField();
        jButton1Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel2.setText("PROBLEMA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel4.setText("OCORREU...");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel6.setText("RECLAMAÇÃO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel8.setText("FEITO POR:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel11.setText("RESOLVIDO?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel13.setText("RESPOSTA:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jTextField1RespostaDoFuncionario.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1RespostaDoFuncionario.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField1RespostaDoFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1RespostaDoFuncionario.setToolTipText("Resposta aqui.");
        jTextField1RespostaDoFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField1RespostaDoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1RespostaDoFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1RespostaDoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 220, 120));

        jButton1EnviarResposta.setBackground(new java.awt.Color(255, 204, 255));
        jButton1EnviarResposta.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jButton1EnviarResposta.setText("ENVIAR");
        jButton1EnviarResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EnviarRespostaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1EnviarResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 90, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entrar em contato:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("bibliotecafdg@hotmail.br");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(12) 00000-0000");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Horário de funcionamento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 452, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Segunda à sexta: 8:00 até 20:00  ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 467, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sábado, Domingo e Feriados: 9::00 até 12:00");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/tinteiro.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 460, 160));

        jTextField2TopicoProblema.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField2TopicoProblema.setText("Tópico do problema");
        getContentPane().add(jTextField2TopicoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jTextField3BibliotecaOuSite.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField3BibliotecaOuSite.setText("Na biblioteca ou no site");
        jTextField3BibliotecaOuSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3BibliotecaOuSiteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3BibliotecaOuSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jTextField4DescricaoDoProblema.setText("Descrição do problema");
        getContentPane().add(jTextField4DescricaoDoProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jTextField5NomeOuAnonimo.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField5NomeOuAnonimo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField5NomeOuAnonimo.setText("Nome da pessoa ou anônimo caso ");
        jTextField5NomeOuAnonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5NomeOuAnonimoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5NomeOuAnonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, 30));

        jTextField6Status.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jTextField6Status.setText("Status");
        getContentPane().add(jTextField6Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jButton1Voltar.setBackground(new java.awt.Color(255, 204, 255));
        jButton1Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jButton1Voltar.setText("VOLTAR");
        getContentPane().add(jButton1Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/RESPOSTA DE AJUDA FUNCIONÁRIO.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1RespostaDoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1RespostaDoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1RespostaDoFuncionarioActionPerformed

    private void jButton1EnviarRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EnviarRespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1EnviarRespostaActionPerformed

    private void jTextField3BibliotecaOuSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3BibliotecaOuSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3BibliotecaOuSiteActionPerformed

    private void jTextField5NomeOuAnonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5NomeOuAnonimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5NomeOuAnonimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaDeAjudaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaDeAjudaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaDeAjudaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaDeAjudaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaDeAjudaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1EnviarResposta;
    private javax.swing.JButton jButton1Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1RespostaDoFuncionario;
    private javax.swing.JTextField jTextField2TopicoProblema;
    private javax.swing.JTextField jTextField3BibliotecaOuSite;
    private javax.swing.JTextField jTextField4DescricaoDoProblema;
    private javax.swing.JTextField jTextField5NomeOuAnonimo;
    private javax.swing.JTextField jTextField6Status;
    // End of variables declaration//GEN-END:variables
}
