/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadegerenciamentodebiblioteca;

/**
 *
 * @author debor
 */
public class ObraSelecionadaBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form ObraSelecionadaBibliotecario
     */
    public ObraSelecionadaBibliotecario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField6TituloSelecionado = new javax.swing.JTextField();
        jTextField5AutorDoTituloSelec = new javax.swing.JTextField();
        jTextField4EditoraDoTituloSelec = new javax.swing.JTextField();
        jTextField3DataPubliDoTituloSelec = new javax.swing.JTextField();
        jTextField2TituloSelecionado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1NumDeCopiasDisp = new javax.swing.JTextField();
        jButton2ModificarObra = new javax.swing.JButton();
        jButton1Emprestimos = new javax.swing.JButton();
        jButton2Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel2.setText("OBRA SELECIONADA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jTextField6TituloSelecionado.setBackground(new java.awt.Color(255, 204, 255));
        jTextField6TituloSelecionado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField6TituloSelecionado.setToolTipText("Título da obra selecionada");
        getContentPane().add(jTextField6TituloSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 220, 60));

        jTextField5AutorDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField5AutorDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField5AutorDoTituloSelec.setToolTipText("Autor da obra selecionada");
        getContentPane().add(jTextField5AutorDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 270, 190, 30));

        jTextField4EditoraDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField4EditoraDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField4EditoraDoTituloSelec.setToolTipText("Editora da obra selecionada");
        getContentPane().add(jTextField4EditoraDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 310, 190, 30));

        jTextField3DataPubliDoTituloSelec.setBackground(new java.awt.Color(255, 204, 255));
        jTextField3DataPubliDoTituloSelec.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField3DataPubliDoTituloSelec.setToolTipText("Data de publicação da obra selecionada");
        jTextField3DataPubliDoTituloSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3DataPubliDoTituloSelecActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3DataPubliDoTituloSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 350, 190, 30));

        jTextField2TituloSelecionado.setBackground(new java.awt.Color(255, 204, 255));
        jTextField2TituloSelecionado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField2TituloSelecionado.setToolTipText("Título da obra selecionada");
        getContentPane().add(jTextField2TituloSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 192, 270, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("N° de cópias disponíveis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 247, -1, -1));

        jTextField1NumDeCopiasDisp.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1NumDeCopiasDisp.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jTextField1NumDeCopiasDisp.setToolTipText("Número de cópias disponíveis");
        getContentPane().add(jTextField1NumDeCopiasDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 70, 30));

        jButton2ModificarObra.setBackground(new java.awt.Color(255, 204, 255));
        jButton2ModificarObra.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2ModificarObra.setText("MODIFICAR OBRA");
        getContentPane().add(jButton2ModificarObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 220, 40));

        jButton1Emprestimos.setBackground(new java.awt.Color(255, 204, 255));
        jButton1Emprestimos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1Emprestimos.setText("EMPRÉSTIMOS");
        getContentPane().add(jButton1Emprestimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 160, 40));

        jButton2Voltar.setBackground(new java.awt.Color(255, 204, 255));
        jButton2Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2Voltar.setText("VOLTAR");
        getContentPane().add(jButton2Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sistemadegerenciamentodebiblioteca/obra selecionada estudanteprofessor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3DataPubliDoTituloSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3DataPubliDoTituloSelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3DataPubliDoTituloSelecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObraSelecionadaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObraSelecionadaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObraSelecionadaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObraSelecionadaBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObraSelecionadaBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Emprestimos;
    private javax.swing.JButton jButton2ModificarObra;
    private javax.swing.JButton jButton2Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1NumDeCopiasDisp;
    private javax.swing.JTextField jTextField2TituloSelecionado;
    private javax.swing.JTextField jTextField3DataPubliDoTituloSelec;
    private javax.swing.JTextField jTextField4EditoraDoTituloSelec;
    private javax.swing.JTextField jTextField5AutorDoTituloSelec;
    private javax.swing.JTextField jTextField6TituloSelecionado;
    // End of variables declaration//GEN-END:variables
}
